name: radio
description: A new Flutter project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  http: ^0.13.6
  location: ^4.4.0
  url_launcher: ^6.1.11
  device_info_plus: ^9.0.0
  shared_preferences: ^2.1.1
  flutter_background_service: ^2.4.6
  flutter_local_notifications: ^14.0.1
  flutter_launcher_icons: ^0.13.1
  external_app_launcher: ^3.1.0
  geolocator: ^9.0.2

flutter_launcher_icons:
  android: true
  image_path: "assets/images.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

